# Config file for automatic testing at travis-ci.org

language: python
sudo: false
matrix:
    include:
    - python: "3.6"
      env: DEPS="wradlib>=1.2.1
                 netCDF4
                 numpy"

# setup adapted from https://github.com/bsmurphy/PyKrige/blob/master/.travis.yml
before_install:
    - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda2/bin:$PATH
    - conda config --prepend channels conda-forge
    - conda update --yes conda
    - conda update --all --yes
    - conda info -a

install:
    - conda create -q -n radola_to_netcdf-env python=${TRAVIS_PYTHON_VERSION} --yes --strict-channel-priority
    - source activate radola_to_netcdf-env
    - conda install --yes $DEPS pip
    - conda install -c conda-forge --yes codecov
    #- pip install coveralls
    - pip install pytest pytest-cov
    - python -V
    #- python setup.py build_ext --inplace
    - python setup.py install
    - pwd
    - du -h

# command to run tests
script:
    - py.test --cov

after_success:
    - codecov
